export type Billboard={id:string;position:number;tier:"hero"|"prime"|"standard";company:string;logo:string;headline:string;subheadline:string;cta:string;price:number;category:string;accent:string;surface:string;surfaceStrong:string;text:string;logoText:string;href:string};

export const billboards:Billboard[]=[
{id:"signalstack",position:1,tier:"hero",company:"SignalStack",logo:"SS",headline:"Ship signals. Not spreadsheets.",subheadline:"Real-time infrastructure for teams building intelligent products.",cta:"See SignalStack",price:14999,category:"Developer Tools",accent:"#DFFF4F",surface:"#11150A",surfaceStrong:"#DFFF4F",text:"#F4F1E8",logoText:"#080808",href:"/company/signalstack"},
{id:"orbitai",position:2,tier:"prime",company:"Orbit AI",logo:"O",headline:"Your next idea has a co-pilot.",subheadline:"AI workflows that turn rough thinking into production work.",cta:"Meet Orbit",price:7999,category:"AI",accent:"#B7A4FF",surface:"#110F19",surfaceStrong:"#B7A4FF",text:"#F4F1E8",logoText:"#080808",href:"/company/orbit-ai"},
{id:"ledgerloop",position:3,tier:"prime",company:"LedgerLoop",logo:"LL",headline:"Finance, without the finance maze.",subheadline:"Modern cash operations for ambitious teams.",cta:"Explore LedgerLoop",price:5999,category:"Fintech",accent:"#72E0C1",surface:"#091613",surfaceStrong:"#72E0C1",text:"#F4F1E8",logoText:"#07110E",href:"/company/ledgerloop"},
{id:"craftcloud",position:4,tier:"prime",company:"CraftCloud",logo:"CC",headline:"Ship beautiful software faster.",subheadline:"A visual system for product teams that care about the details.",cta:"Discover CraftCloud",price:3999,category:"SaaS",accent:"#FF9B6A",surface:"#1A100C",surfaceStrong:"#FF9B6A",text:"#F4F1E8",logoText:"#160B06",href:"/company/craftcloud"},
{id:"foundry",position:5,tier:"standard",company:"Foundry",logo:"F",headline:"Build once. Learn every launch.",subheadline:"Product intelligence for modern growth teams.",cta:"Visit Foundry",price:1999,category:"Growth",accent:"#9FC8FF",surface:"#0C121A",surfaceStrong:"#9FC8FF",text:"#F4F1E8",logoText:"#08101A",href:"/company/foundry"},
{id:"arcade",position:6,tier:"standard",company:"Arcade",logo:"A",headline:"Make work feel lighter.",subheadline:"Tiny automations with a surprisingly big payoff.",cta:"Try Arcade",price:999,category:"Productivity",accent:"#FF7DC5",surface:"#190D15",surfaceStrong:"#FF7DC5",text:"#F4F1E8",logoText:"#170913",href:"/company/arcade"}];
export const categories=["AI","SaaS","Fintech","Developer Tools","Consumer","Growth"];